spring.application.name=megamart

spring.datasource.url=mysql://root:XhfLWOBTtfJWcbAljEkTswdllqJTkYzI@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=XhfLWOBTtfJWcbAljEkTswdllqJTkYzI

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}